//$file${.::ros_sm.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: ros.qm
// File:  ${.::ros_sm.c}
//
// This code has been generated by QM 6.1.1 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open source software: you can redistribute it under
// the terms of the GNU General Public License as published by the Free
// Software Foundation.
//
// This code is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
// more details.
//
// NOTE:
// Alternatively, this generated code may be distributed under the terms
// of Quantum Leaps commercial licenses, which expressly supersede the GNU
// General Public License and are specifically designed for licensees
// interested in retaining the proprietary status of their code.
//
// Contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${.::ros_sm.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#include "all.h"


//$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
// Check for the minimum required QP version
#if (QP_VERSION < 730U) || (QP_VERSION != ((QP_RELEASE^4294967295U) % 0x3E8U))
#error qpc version 7.3.0 or higher required
#endif
//$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//$define${AOs::ros} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::ros} ................................................................

//${AOs::ros::SM} ............................................................
QState ros_initial(ros * const me, void const * const par) {
    static struct {
        QMState const *target;
        QActionHandler act[2];
    } const tatbl_ = { // tran-action table
        &ros_on_s, // target state
        {
            Q_ACTION_CAST(&ros_on_e), // entry
            Q_ACTION_NULL // zero terminator
        }
    };
    //${AOs::ros::SM::initial}
    rosInitial(me,par);

    QS_FUN_DICTIONARY(&ros_on);

    return QM_TRAN_INIT(&tatbl_);
}

//${AOs::ros::SM::on} ........................................................
QMState const ros_on_s = {
    QM_STATE_NULL, // superstate (top)
    Q_STATE_CAST(&ros_on),
    Q_ACTION_CAST(&ros_on_e),
    Q_ACTION_NULL, // no exit action
    Q_ACTION_NULL  // no initial tran.
};
//${AOs::ros::SM::on}
QState ros_on_e(ros * const me) {
    rosOnEntry(me);
    return QM_ENTRY(&ros_on_s);
}
//${AOs::ros::SM::on}
QState ros_on(ros * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::ros::SM::on::TOUT}
        case TOUT_SIG: {
            rosTout(me,e);
            status_ = QM_HANDLED();
            break;
        }
        //${AOs::ros::SM::on::KEY}
        case KEY_SIG: {
            rosParse(me,e);
            status_ = QM_HANDLED();
            break;
        }
        //${AOs::ros::SM::on::BTN1}
        case BTN1_SIG: {
            rosBtn1(me,e);
            status_ = QM_HANDLED();
            break;
        }
        //${AOs::ros::SM::on::BTN2}
        case BTN2_SIG: {
            rosBtn2(me,e);
            status_ = QM_HANDLED();
            break;
        }
        //${AOs::ros::SM::on::BTN3}
        case BTN3_SIG: {
            rosBtn3(me,e);
            status_ = QM_HANDLED();
            break;
        }
        //${AOs::ros::SM::on::BTN4}
        case BTN4_SIG: {
            rosBtn4(me,e);
            status_ = QM_HANDLED();
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}
//$enddef${AOs::ros} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
