//$file${.::btn_sm.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: btn.qm
// File:  ${.::btn_sm.c}
//
// This code has been generated by QM 6.1.1 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open source software: you can redistribute it under
// the terms of the GNU General Public License as published by the Free
// Software Foundation.
//
// This code is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
// more details.
//
// NOTE:
// Alternatively, this generated code may be distributed under the terms
// of Quantum Leaps commercial licenses, which expressly supersede the GNU
// General Public License and are specifically designed for licensees
// interested in retaining the proprietary status of their code.
//
// Contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${.::btn_sm.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#include "inc.h"

//$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
// Check for the minimum required QP version
#if (QP_VERSION < 730U) || (QP_VERSION != ((QP_RELEASE^4294967295U) % 0x3E8U))
#error qpc version 7.3.0 or higher required
#endif
//$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//$define${AOs::btn} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::btn} ................................................................

//${AOs::btn::SM} ............................................................
QState btn_initial(btn * const me, void const * const par) {
    //${AOs::btn::SM::initial}
    btnInitial(me,par);
    return Q_TRAN(&btn_idle);
}

//${AOs::btn::SM::idle} ......................................................
QState btn_idle(btn * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::btn::SM::idle::TOUT}
        case TOUT_SIG: {
            btnDrvPool();
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::btn::SM::idle::BTN1}
        case BTN1_SIG: {
            status_ = Q_TRAN(&btn_btn1);
            break;
        }
        //${AOs::btn::SM::idle::BTN2}
        case BTN2_SIG: {
            status_ = Q_TRAN(&btn_btn2);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

//${AOs::btn::SM::idle::btn1} ................................................
QState btn_btn1(btn * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::btn::SM::idle::btn1}
        case Q_ENTRY_SIG: {
            btn1Entry(me,e);
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::btn::SM::idle::btn1::BTN2}
        case BTN2_SIG: {
            status_ = Q_TRAN(&btn_btn2);
            break;
        }
        //${AOs::btn::SM::idle::btn1::BTN1}
        case BTN1_SIG: {
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&btn_idle);
            break;
        }
    }
    return status_;
}

//${AOs::btn::SM::idle::btn2} ................................................
QState btn_btn2(btn * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::btn::SM::idle::btn2}
        case Q_ENTRY_SIG: {
            btn2Entry(me,e);
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::btn::SM::idle::btn2::BTN1}
        case BTN1_SIG: {
            status_ = Q_TRAN(&btn_btn1);
            break;
        }
        //${AOs::btn::SM::idle::btn2::BTN2}
        case BTN2_SIG: {
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&btn_idle);
            break;
        }
    }
    return status_;
}
//$enddef${AOs::btn} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
