//$file${.::led_sm.h} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: led.qm
// File:  ${.::led_sm.h}
//
// This code has been generated by QM 6.1.1 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open source software: you can redistribute it under
// the terms of the GNU General Public License as published by the Free
// Software Foundation.
//
// This code is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
// more details.
//
// NOTE:
// Alternatively, this generated code may be distributed under the terms
// of Quantum Leaps commercial licenses, which expressly supersede the GNU
// General Public License and are specifically designed for licensees
// interested in retaining the proprietary status of their code.
//
// Contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${.::led_sm.h} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#ifndef LED_SM
#define LED_SM

//$declare${AOs::led} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::led} ................................................................
typedef struct {
// protected:
    QMActive super;

// private:
    QTimeEvt timeEvt;

// private submachines
    // exit points for submachine ${AOs::led::SM::ledToogle}
    struct SM_ledToogle {
        QMState super;
        QActionHandler const XP; // eXit-Point segment
    } const *sub_ledToogle;
} led;

// protected:
QState led_initial(led * const me, void const * const par);
QState led_on  (led * const me, QEvt const * const e);
extern QMState const led_on_s;
QState led_off  (led * const me, QEvt const * const e);
extern QMState const led_off_s;
QState led_state  (led * const me, QEvt const * const e);
QState led_state_e(led * const me);
QState led_state_XP(led * const me);
extern struct SM_ledToogle const led_state_s;

// submachine ${AOs::led::SM::ledToogle}
QState led_ledToogle  (led * const me, QEvt const * const e);
QState led_ledToogle_x(led * const me);
extern QMState const led_ledToogle_s;
QState led_ledToogle_red_ep(led * const me);
QState led_ledToogle_on  (led * const me, QEvt const * const e);
extern QMState const led_ledToogle_on_s;
QState led_ledToogle_off  (led * const me, QEvt const * const e);
extern QMState const led_ledToogle_off_s;
//$enddecl${AOs::led} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

#endif
