//$file${.::led_sm.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: led.qm
// File:  ${.::led_sm.c}
//
// This code has been generated by QM 6.1.1 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open source software: you can redistribute it under
// the terms of the GNU General Public License as published by the Free
// Software Foundation.
//
// This code is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
// more details.
//
// NOTE:
// Alternatively, this generated code may be distributed under the terms
// of Quantum Leaps commercial licenses, which expressly supersede the GNU
// General Public License and are specifically designed for licensees
// interested in retaining the proprietary status of their code.
//
// Contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${.::led_sm.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#include "all.h"


//$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
// Check for the minimum required QP version
#if (QP_VERSION < 730U) || (QP_VERSION != ((QP_RELEASE^4294967295U) % 0x3E8U))
#error qpc version 7.3.0 or higher required
#endif
//$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//$define${AOs::led} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::led} ................................................................

//${AOs::led::SM} ............................................................
QState led_initial(led * const me, void const * const par) {
    static QMTranActTable const tatbl_ = { // tran-action table
        &led_idle_s, // target state
        {
            Q_ACTION_NULL // zero terminator
        }
    };
    //${AOs::led::SM::initial}
    ledInitial(me,par);

    QS_FUN_DICTIONARY(&led_idle);
    QS_FUN_DICTIONARY(&led_on);
    QS_FUN_DICTIONARY(&led_off);
    QS_FUN_DICTIONARY(&led_state);
    QS_FUN_DICTIONARY(&led_ledToogle_on);
    QS_FUN_DICTIONARY(&led_ledToogle_off);
    QS_FUN_DICTIONARY(&led_ledToogle);

    return QM_TRAN_INIT(&tatbl_);
}

//${AOs::led::SM::idle} ......................................................
QMState const led_idle_s = {
    QM_STATE_NULL, // superstate (top)
    Q_STATE_CAST(&led_idle),
    Q_ACTION_NULL, // no entry action
    Q_ACTION_NULL, // no exit action
    Q_ACTION_NULL  // no initial tran.
};
//${AOs::led::SM::idle}
QState led_idle(led * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::led::SM::idle::LEDR}
        case LEDR_SIG: {
            ledSetRed(me,e);
            status_ = QM_HANDLED();
            break;
        }
        //${AOs::led::SM::idle::LEDG}
        case LEDG_SIG: {
            ledSetGreen(me,e);
            status_ = QM_HANDLED();
            break;
        }
        //${AOs::led::SM::idle::LEDB}
        case LEDB_SIG: {
            ledSetBlue(me,e);
            status_ = QM_HANDLED();
            break;
        }
        //${AOs::led::SM::idle::TOUT}
        case TOUT_SIG: {
            ledTout(me,e);
            status_ = QM_HANDLED();
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}

//${AOs::led::SM::idle::on} ..................................................
QMState const led_on_s = {
    &led_idle_s, // superstate
    Q_STATE_CAST(&led_on),
    Q_ACTION_NULL, // no entry action
    Q_ACTION_NULL, // no exit action
    Q_ACTION_NULL  // no initial tran.
};
//${AOs::led::SM::idle::on}
QState led_on(led * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::led::SM::idle::on::TOUT}
        case TOUT_SIG: {
            static QMTranActTable const tatbl_ = { // tran-action table
                &led_off_s, // target state
                {
                    Q_ACTION_NULL // zero terminator
                }
            };
            ledDrvGreen(0);
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}

//${AOs::led::SM::idle::off} .................................................
QMState const led_off_s = {
    &led_idle_s, // superstate
    Q_STATE_CAST(&led_off),
    Q_ACTION_NULL, // no entry action
    Q_ACTION_NULL, // no exit action
    Q_ACTION_NULL  // no initial tran.
};
//${AOs::led::SM::idle::off}
QState led_off(led * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::led::SM::idle::off::TOUT}
        case TOUT_SIG: {
            static struct {
                QMState const *target;
                QActionHandler act[3];
            } const tatbl_ = { // tran-action table
                &led_ledToogle_s, // target submachine
                {
                    Q_ACTION_CAST(&led_state_e), // entry
                    Q_ACTION_CAST(&led_ledToogle_red_ep), // EP
                    Q_ACTION_NULL // zero terminator
                }
            };
            status_ = QM_TRAN_EP(&tatbl_);
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}

//${AOs::led::SM::idle::state} ...............................................
struct SM_ledToogle const led_state_s = {
    {
        &led_idle_s, // superstate
        Q_STATE_CAST(&led_state),
        Q_ACTION_CAST(&led_state_e),
        Q_ACTION_NULL, // no exit action
        Q_ACTION_NULL  // no initial tran.
    }
    ,Q_ACTION_CAST(&led_state_XP)
};
//${AOs::led::SM::idle::state}
QState led_state_e(led * const me) {
    me->sub_ledToogle = &led_state_s; // attach submachine
    return QM_ENTRY(&led_state_s.super);
}
//${AOs::led::SM::idle::state}
QState led_state_XP(led * const me) {
    static struct {
        QMState const *target;
        QActionHandler act[2];
    } const tatbl_ = { // tran-action table
        &led_on_s, // target state
        {
            Q_ACTION_CAST(&led_ledToogle_x), // submachine exit
            Q_ACTION_NULL // zero terminator
        }
    };
    Q_UNUSED_PAR(me);
    ledDrvGreen(1);
    return QM_TRAN(&tatbl_);
}
//${AOs::led::SM::idle::state}
QState led_state(led * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    Q_UNUSED_PAR(me);
    return status_;
}

//${AOs::led::SM::ledToogle} .................................................
//${AOs::led::SM::ledToogle}
QMState const led_ledToogle_s = {
    QM_STATE_NULL, // superstate unused
    Q_STATE_CAST(&led_ledToogle),
    Q_ACTION_NULL, // no entry action
    Q_ACTION_CAST(&led_ledToogle_x),
    Q_ACTION_NULL  // no initial tran.
};
//${AOs::led::SM::ledToogle}
QState led_ledToogle_x(led * const me) {
    return QM_SM_EXIT(&me->sub_ledToogle->super);
}
//${AOs::led::SM::ledToogle}
QState led_ledToogle(led * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        default: {
            status_ = QM_SUPER_SUB(&me->sub_ledToogle->super);
            break;
        }
    }
    Q_UNUSED_PAR(me);
    return status_;
}
//${AOs::led::SM::ledToogle::EP-red}
QState led_ledToogle_red_ep(led * const me) {
    static QMTranActTable const tatbl_ = { // tran-action table
        &led_ledToogle_on_s, // target state
        {
            Q_ACTION_NULL // zero terminator
        }
    };
    ledDrvRed(1);
    return QM_TRAN_EP(&tatbl_);
}

//${AOs::led::SM::ledToogle::on} .............................................
QMState const led_ledToogle_on_s = {
    &led_ledToogle_s, // superstate
    Q_STATE_CAST(&led_ledToogle_on),
    Q_ACTION_NULL, // no entry action
    Q_ACTION_NULL, // no exit action
    Q_ACTION_NULL  // no initial tran.
};
//${AOs::led::SM::ledToogle::on}
QState led_ledToogle_on(led * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::led::SM::ledToogle::on::TOUT}
        case TOUT_SIG: {
            static QMTranActTable const tatbl_ = { // tran-action table
                &led_ledToogle_off_s, // target state
                {
                    Q_ACTION_NULL // zero terminator
                }
            };
            ledDrvRed(0);
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}

//${AOs::led::SM::ledToogle::off} ............................................
QMState const led_ledToogle_off_s = {
    &led_ledToogle_s, // superstate
    Q_STATE_CAST(&led_ledToogle_off),
    Q_ACTION_NULL, // no entry action
    Q_ACTION_NULL, // no exit action
    Q_ACTION_NULL  // no initial tran.
};
//${AOs::led::SM::ledToogle::off}
QState led_ledToogle_off(led * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::led::SM::ledToogle::off::TOUT}
        case TOUT_SIG: {
            static QMTranActTable const tatbl_ = { // tran-action table
                &led_ledToogle_s, // target submachine
                {
                    Q_ACTION_NULL // zero terminator
                }
            };
            status_ = QM_TRAN_XP(me->sub_ledToogle->XP, &tatbl_);
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}
//$enddef${AOs::led} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
