//$file${.::blinky.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: blinky.qm
// File:  ${.::blinky.c}
//
// This code has been generated by QM 6.1.1 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open source software: you can redistribute it under
// the terms of the GNU General Public License as published by the Free
// Software Foundation.
//
// This code is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
// more details.
//
// NOTE:
// Alternatively, this generated code may be distributed under the terms
// of Quantum Leaps commercial licenses, which expressly supersede the GNU
// General Public License and are specifically designed for licensees
// interested in retaining the proprietary status of their code.
//
// Contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${.::blinky.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#include "all.h"


//$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
// Check for the minimum required QP version
#if (QP_VERSION < 730U) || (QP_VERSION != ((QP_RELEASE^4294967295U) % 0x3E8U))
#error qpc version 7.3.0 or higher required
#endif
//$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//$define${AOs::ao} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::ao} .................................................................

//${AOs::ao::SM} .............................................................
QState ao_initial(ao * const me, void const * const par) {
    static struct {
        QMState const *target;
        QActionHandler act[2];
    } const tatbl_ = { // tran-action table
        &ao_state1_s, // target state
        {
            Q_ACTION_CAST(&ao_state1_e), // entry
            Q_ACTION_NULL // zero terminator
        }
    };
    //${AOs::ao::SM::initial}
    init(me,par);
    return QM_TRAN_INIT(&tatbl_);
}

//${AOs::ao::SM::state3} .....................................................
QMState const ao_state3_s = {
    QM_STATE_NULL, // superstate (top)
    Q_STATE_CAST(&ao_state3),
    Q_ACTION_NULL, // no entry action
    Q_ACTION_NULL, // no exit action
    Q_ACTION_NULL  // no initial tran.
};
//${AOs::ao::SM::state3}
QState ao_state3(ao * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::ao::SM::state3::SIG3}
        case SIG3_SIG: {
            tout(me,e);
            status_ = QM_HANDLED();
            break;
        }
        //${AOs::ao::SM::state3::TRIG}
        case TRIG_SIG: {
            static struct {
                QMState const *target;
                QActionHandler act[3];
            } const tatbl_ = { // tran-action table
                &ao_sub_s, // target submachine
                {
                    Q_ACTION_CAST(&ao_state_e), // entry
                    Q_ACTION_CAST(&ao_sub_EP_ep), // EP
                    Q_ACTION_NULL // zero terminator
                }
            };
            status_ = QM_TRAN_EP(&tatbl_);
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}

//${AOs::ao::SM::state3::state1} .............................................
QMState const ao_state1_s = {
    &ao_state3_s, // superstate
    Q_STATE_CAST(&ao_state1),
    Q_ACTION_CAST(&ao_state1_e),
    Q_ACTION_CAST(&ao_state1_x),
    Q_ACTION_NULL  // no initial tran.
};
//${AOs::ao::SM::state3::state1}
QState ao_state1_e(ao * const me) {
    state1Entry(me);
    return QM_ENTRY(&ao_state1_s);
}
//${AOs::ao::SM::state3::state1}
QState ao_state1_x(ao * const me) {
    state1Exit(me);
    return QM_EXIT(&ao_state1_s);
}
//${AOs::ao::SM::state3::state1}
QState ao_state1(ao * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::ao::SM::state3::state1::SIG1}
        case SIG1_SIG: {
            static struct {
                QMState const *target;
                QActionHandler act[3];
            } const tatbl_ = { // tran-action table
                &ao_state2_s, // target state
                {
                    Q_ACTION_CAST(&ao_state1_x), // exit
                    Q_ACTION_CAST(&ao_state2_e), // entry
                    Q_ACTION_NULL // zero terminator
                }
            };
            sig1(me,e);
            status_ = QM_TRAN(&tatbl_);
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}

//${AOs::ao::SM::state3::state2} .............................................
QMState const ao_state2_s = {
    &ao_state3_s, // superstate
    Q_STATE_CAST(&ao_state2),
    Q_ACTION_CAST(&ao_state2_e),
    Q_ACTION_CAST(&ao_state2_x),
    Q_ACTION_NULL  // no initial tran.
};
//${AOs::ao::SM::state3::state2}
QState ao_state2_e(ao * const me) {
    state2Entry(me);
    return QM_ENTRY(&ao_state2_s);
}
//${AOs::ao::SM::state3::state2}
QState ao_state2_x(ao * const me) {
    state2Exit(me);
    return QM_EXIT(&ao_state2_s);
}
//${AOs::ao::SM::state3::state2}
QState ao_state2(ao * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::ao::SM::state3::state2::SIG2}
        case SIG2_SIG: {
            sig2(me,e);
            //${AOs::ao::SM::state3::state2::SIG2::[compare(me,e)==0]}
            if (compare(me,e)==0) {
                static struct {
                    QMState const *target;
                    QActionHandler act[3];
                } const tatbl_ = { // tran-action table
                    &ao_state1_s, // target state
                    {
                        Q_ACTION_CAST(&ao_state2_x), // exit
                        Q_ACTION_CAST(&ao_state1_e), // entry
                        Q_ACTION_NULL // zero terminator
                    }
                };
                accepted(me,e);
                status_ = QM_TRAN(&tatbl_);
            }
            //${AOs::ao::SM::state3::state2::SIG2::[else]}
            else {
                static struct {
                    QMState const *target;
                    QActionHandler act[3];
                } const tatbl_ = { // tran-action table
                    &ao_state1_s, // target state
                    {
                        Q_ACTION_CAST(&ao_state2_x), // exit
                        Q_ACTION_CAST(&ao_state1_e), // entry
                        Q_ACTION_NULL // zero terminator
                    }
                };
                notAccepted(me,e);
                status_ = QM_TRAN(&tatbl_);
            }
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}

//${AOs::ao::SM::state} ......................................................
struct SM_sub const ao_state_s = {
    {
        QM_STATE_NULL, // superstate (top)
        Q_STATE_CAST(&ao_state),
        Q_ACTION_CAST(&ao_state_e),
        Q_ACTION_NULL, // no exit action
        Q_ACTION_NULL  // no initial tran.
    }
    ,Q_ACTION_CAST(&ao_state_XP)
};
//${AOs::ao::SM::state}
QState ao_state_e(ao * const me) {
    me->sub_sub = &ao_state_s; // attach submachine
    return QM_ENTRY(&ao_state_s.super);
}
//${AOs::ao::SM::state}
QState ao_state_XP(ao * const me) {
    static struct {
        QMState const *target;
        QActionHandler act[4];
    } const tatbl_ = { // tran-action table
        &ao_sub_s, // target submachine
        {
            Q_ACTION_CAST(&ao_sub_x), // submachine exit
            Q_ACTION_CAST(&ao_state_e), // entry
            Q_ACTION_CAST(&ao_sub_EP_ep), // EP
            Q_ACTION_NULL // zero terminator
        }
    };
    Q_UNUSED_PAR(me);
    return QM_TRAN(&tatbl_);
}
//${AOs::ao::SM::state}
QState ao_state(ao * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    Q_UNUSED_PAR(me);
    return status_;
}

//${AOs::ao::SM::state} ......................................................
struct SM_sub const ao_state_s = {
    {
        QM_STATE_NULL, // superstate (top)
        Q_STATE_CAST(&ao_state),
        Q_ACTION_CAST(&ao_state_e),
        Q_ACTION_NULL, // no exit action
        Q_ACTION_NULL  // no initial tran.
    }
    ,Q_ACTION_CAST(&ao_state_XP)
};
//${AOs::ao::SM::state}
QState ao_state_e(ao * const me) {
    me->sub_sub = &ao_state_s; // attach submachine
    return QM_ENTRY(&ao_state_s.super);
}
//${AOs::ao::SM::state}
QState ao_state_XP(ao * const me) {
    static struct {
        QMState const *target;
        QActionHandler act[2];
    } const tatbl_ = { // tran-action table
        &ao_state3_s, // target state
        {
            Q_ACTION_CAST(&ao_sub_x), // submachine exit
            Q_ACTION_NULL // zero terminator
        }
    };
    Q_UNUSED_PAR(me);
    return QM_TRAN(&tatbl_);
}
//${AOs::ao::SM::state}
QState ao_state(ao * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    Q_UNUSED_PAR(me);
    return status_;
}

//${AOs::ao::SM::sub} ........................................................
//${AOs::ao::SM::sub}
QMState const ao_sub_s = {
    QM_STATE_NULL, // superstate unused
    Q_STATE_CAST(&ao_sub),
    Q_ACTION_NULL, // no entry action
    Q_ACTION_CAST(&ao_sub_x),
    Q_ACTION_NULL  // no initial tran.
};
//${AOs::ao::SM::sub}
QState ao_sub_x(ao * const me) {
    return QM_SM_EXIT(&me->sub_sub->super);
}
//${AOs::ao::SM::sub}
QState ao_sub(ao * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        default: {
            status_ = QM_SUPER_SUB(&me->sub_sub->super);
            break;
        }
    }
    Q_UNUSED_PAR(me);
    return status_;
}
//${AOs::ao::SM::sub::EP-EP}
QState ao_sub_EP_ep(ao * const me) {
    static QMTranActTable const tatbl_ = { // tran-action table
        &ao_sub_state_s, // target state
        {
            Q_ACTION_NULL // zero terminator
        }
    };
    return QM_TRAN_EP(&tatbl_);
}

//${AOs::ao::SM::sub::state} .................................................
QMState const ao_sub_state_s = {
    &ao_sub_s, // superstate
    Q_STATE_CAST(&ao_sub_state),
    Q_ACTION_NULL, // no entry action
    Q_ACTION_NULL, // no exit action
    Q_ACTION_NULL  // no initial tran.
};
//${AOs::ao::SM::sub::state}
QState ao_sub_state(ao * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::ao::SM::sub::state::TRIG}
        case TRIG_SIG: {
            static QMTranActTable const tatbl_ = { // tran-action table
                &ao_sub_s, // target submachine
                {
                    Q_ACTION_NULL // zero terminator
                }
            };
            status_ = QM_TRAN_XP(me->sub_sub->XP, &tatbl_);
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}
//$enddef${AOs::ao} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
